version: '3.8'

services:
  envoy:
    image: envoyproxy/ai-gateway:v0.1.0
    container_name: envoy-ai-gateway
    volumes:
      - ./envoy_configs/envoy_config.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9000:9000"  # API port
      - "9901:9901"  # Admin dashboard
    environment:
      - ENVOY_UID=0
      - ENVOY_GID=0
    restart: unless-stopped
    networks:
      - ai-gateway-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ai-gateway-network

  streamlit:
    build:
      context: .
      dockerfile: ./streamlit_app/Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
    environment:
      - GATEWAY_URL=http://envoy:9000
      - PYTHONPATH=/app
    depends_on:
      - envoy
      - ollama
    networks:
      - ai-gateway-network
    restart: unless-stopped

  adk-agents:
    build:
      context: .
      dockerfile: ./agent_configs/Dockerfile
    container_name: adk-agents
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/google-credentials.json
      - GATEWAY_URL=http://envoy:9000
    volumes:
      - ./agent_configs:/app
      - ./credentials:/app/credentials
    depends_on:
      - envoy
    networks:
      - ai-gateway-network
    restart: unless-stopped

networks:
  ai-gateway-network:
    driver: bridge

volumes:
  ollama-models:
